# Generated by Django 3.0.5 on 2020-04-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shuyuadmin.Menu')),
            ],
            options={
                'verbose_name_plural': '菜单管理',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('url', models.CharField(max_length=256)),
                ('app_name', models.CharField(max_length=32)),
                ('table_name', models.CharField(max_length=32)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shuyuadmin.Menu')),
            ],
            options={
                'verbose_name_plural': '权限管理',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('choice1', models.SmallIntegerField(choices=[(1, '16G'), (2, '32G'), (3, '4G'), (4, '8G')], verbose_name='内存容量')),
                ('choice2', models.SmallIntegerField(choices=[(1, '集成显卡'), (2, '独立显卡')], verbose_name='显卡类型')),
                ('choice3', models.SmallIntegerField(choices=[(1, 'Windows 10'), (2, 'Mac OS'), (3, 'Linux')], verbose_name='操作系统')),
                ('size', models.CharField(max_length=10)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': '产品管理',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('permissions', models.ManyToManyField(to='shuyuadmin.Permission')),
            ],
            options={
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('roles', models.ManyToManyField(to='shuyuadmin.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
