# Generated by Django 3.0.5 on 2020-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuyuadmin', '0002_auto_20200413_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('choice1', models.SmallIntegerField(choices=[(1, '16G'), (2, '32G'), (3, '4G'), (4, '8G')], verbose_name='内存容量')),
                ('choice2', models.SmallIntegerField(choices=[(1, '集成显卡'), (2, '独立显卡')], verbose_name='显卡类型')),
                ('choice3', models.SmallIntegerField(choices=[(1, 'Windows 10'), (2, 'Mac OS'), (3, 'Linux')], verbose_name='操作系统')),
                ('size', models.CharField(max_length=10)),
                ('comment', models.TextField()),
            ],
        ),
    ]
