# Generated by Django 3.0.5 on 2020-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuyuadmin', '0002_auto_20200413_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='app_name',
            field=models.CharField(max_length=32, verbose_name='应用名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='table_name',
            field=models.CharField(max_length=32, verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
    ]
